name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build fat jar
        run: ./gradlew fatJar
      - name: Check grammar
        run: ./gradlew generateGrammarSource
      - name: Check main style
        run: ./gradlew checkstyleMain
      - name: Check test style
        run: ./gradlew checkstyleTest
      - name: Build war
        run: ./gradlew war
      - name: Install node deps
        run: npm install
      - name: Build
        run: bash ./support/make.sh
      - name: Install front end deps
        run: bash ./support/install_deps.sh
      - name: Install browser
        run: sudo apt install -y chromium-browser
      - name: Run unit tests
        run: grunt
